### ISSUE TITLE
invalid transform matrix with CTF parameter

### ISSUE THREAD

**Issue by McHaillet** [KosinskiLab/pyTME#14]
Hi Valentin!

I was trying the latest version (0.2.3) from pypi and ran into an issue with the transformation matrix creation.

This is my command:

```
match_template.py --target dataset/tomo200528_100.mrc --template templates/60S.mrc --template_mask templates/mask.mrc -o pytme_60S/output.pickle -a 7.00 --use_gpu --gpu_indices 0 --tilt_angles 51,48 --defocus 23000 --acceleration_voltage 200 --amplitude_contrast 0.08 --wedge_axes 0,2
```

This is the ouput:

```
********************************************************************************
*                                 pytme v0.2.3                                 *
********************************************************************************

> Target
  - Initial Shape:       (250, 478, 462)
  - Sampling Rate:       (13.79, 13.79, 13.79)
  - Final Shape:         (250, 478, 462)
/home/marten/coding/pyTME/tme/backends/npfftw_backend.py:417: RuntimeWarning: invalid value encountered in divide
  center_of_mass = [self.sum((arr * grid) / denominator) for grid in grids]

> Template
  - Initial Shape:       (60, 60, 60)
  - Sampling Rate:       (13.79, 13.79, 13.79)
  - Final Shape:         (105, 105, 105)
Traceback (most recent call last):
  File "/home/marten/miniconda3/envs/pytme/bin/match_template.py", line 1136, in <module>
    main()
  File "/home/marten/miniconda3/envs/pytme/bin/match_template.py", line 915, in main
    template_mask = template_mask.rigid_transform(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marten/coding/pyTME/tme/density.py", line 1657, in rigid_transform
    NumpyFFTWBackend().rigid_transform(
  File "/home/marten/coding/pyTME/tme/backends/npfftw_backend.py", line 363, in rigid_transform
    self._rigid_transform(
  File "/home/marten/coding/pyTME/tme/backends/npfftw_backend.py", line 328, in _rigid_transform
    self.affine_transform(
  File "/home/marten/miniconda3/envs/pytme/lib/python3.12/site-packages/scipy/ndimage/_interpolation.py", line 600, in affine_transform
    raise ValueError(msg)
ValueError: Expected homogeneous transformation matrix with shape (4, 4) for image shape (105, 105, 105), but bottom row was not equal to [0, 0, 0, 1]
```

If I remove the CTF parameters the program seems to run as expected, i.e. with this command:

```
match_template.py --target dataset/tomo200528_100.mrc --template templates/60S_ctf.mrc --template_mask templates/mask_80px.mrc -o pytme_60S/output.pickle -a 7.00 --use_gpu --gpu_indices 0 --tilt_angles 51,48 --wedge_axes 0,2
```

After some print statements, I found that at least in [this line](https://github.com/KosinskiLab/pyTME/blob/62acfa47f750420116bc858b910ce3bcf480da8a/tme/backends/npfftw_backend.py#L349) the `translation` parameter contains NaN values. As a temporary workaround I changed the line to this:

```python
translation = self.zeros(arr.ndim) if translation is None or self.isnan(translation).any() else translation
```

but I didn't track further to the source of those NaN's.

**Comment by maurerv** [comment]
Hi Marten,

Thank you for reaching out :)

I think pytme is having issues centering your template. By default, centering only considers non-negative densities. If your template consists exclusively of negative densities, this will lead to a zero-division error.

If your template is already centered, you can add the `--no_centering` flag to omit the centering step

**Comment by McHaillet** [comment]
ah! Yup, the template is indeed negative and adding no_centering does it make work.
Thanks!

**Comment by McHaillet** [comment]
Is the template expected to be white or black if I provide the CTF options?

**Comment by maurerv** [comment]
Glad to hear that got you started :)

As long as you are not using `--no_flip_phase`, the template is expected to match the contrast of the target. If in doubt, you can also have a look at the CTF filter in preprocessor_gui.py, which exposes the majority of parameters available in match_template.py

**Comment by McHaillet** [comment]
Thanks for the answer!

> I think pytme is having issues centering your template. By default, centering only considers non-negative densities. If your template consists exclusively of negative densities, this will lead to a zero-division error.

By the way, we managed to get this to work by taking the square of the input density to do automated centering for positive and negative contrast templates. Works quite well!

**Comment by maurerv** [comment]
No worries, glad it was helpful. Thanks for the suggestion as well! Its definitely warranted, considering the potential issues with negative contrast templates. Assuming the changes are compatible with our in-house integrations, I might include it in a future version.

I will go ahead and close the issue, but feel free to re-open or create a new issue if need be :)
