### ISSUE TITLE
Minor Improvement: hi low score threshold for extraction

### ISSUE THREAD

**Issue by shahpnmlab** [KosinskiLab/pyTME#3]
Hi,
I was wondering if it would be better to select extraction points as a function of hi-low CC threshold rather than picking n points. One of the outputs of the matching program could be the mean CC, score and hi, low values and the user can then decide where to set the thresholds during the extraction step.
Best,
Pranav

**Comment by maurerv** [comment]
Hi @shahpnmlab,

Thank you for the suggestion!

We are currently testing a feature like this. Until that is released, analyzing the score distribution in the orientations file from postprocess.py could serve as a workaround to achieve your goal. If you have an estimate of the CC range your true positives fall into, filtering based on hi-low CC should indeed be more precise than just picking top N points.

Best,
Valentin

**Comment by shahpnmlab** [comment]
Thanks1 Looking forward to the feature! IN the meantime will use your suggestion.

**Comment by maurerv** [comment]
Hi @shahpnmlab,

We added support for specifying minimum and maximum score cutoffs in 6556dda901ede97ba8581c1610f93ccdfafa4b68. postprocess.py now also provides options for automatically determining score cutoffs.

I hope this enables you to keep going! I will close this issue for the time being, but feel free to re-open :)
