### ISSUE TITLE
Documentation regarding output of match_template.py

### ISSUE THREAD

**Issue by DimitriosBellos** [KosinskiLab/pyTME#4]
Dear developers,

Hi my name is Dimitrios Bellos and I am member of the AI & I theme in the Rosalind Franklin Institute, UK. We are interested in using your software for particle picking. We have start using it and reading through the documentation (https://kosinskilab.github.io/pyTME/quickstart/match_template.html), however we would some help interpreting the output of the `match_template.py` command-line tool (output.pickle) . Can you please help us or gives an example of how to take it apart e.g. which part the coordinates of the candidates, scores for each candidate, etc. ?

Thank you in advance for your time reading and responding to us.

Kind regards,
Dimitrios Bellos

**Comment by maurerv** [comment]
Hi @DimitriosBellos,

the output of `match_template.py` is further explained in the postprocessing section: https://kosinskilab.github.io/pyTME/quickstart/postprocessing.html#template-matching-output. The pickle file itself can be opened using the [load_pickle](https://kosinskilab.github.io/pyTME/reference/api/tme.matching_utils.load_pickle.html#tme.matching_utils.load_pickle) function. Perhaps this can be highlighted better in the documentation.

Thank you for your input and feel free to reach out if you have further questions.

Best,
Valentin
