### ISSUE TITLE
reshape issue in match_template

### ISSUE THREAD

**Issue by McHaillet** [KosinskiLab/pyTME#5]
Hi @maurerv !

Your template matching software is looking really nice!

I was curious to benchmark it versus my package [pytom-match-pick](https://github.com/SBC-Utrecht/pytom-match-pick) as your paper showed the original performance in pytom was definitely sub-par, but I now made some updates and hoping it should be more equal :)

I am running into the following issue though when running match_template.py with the cupy gpu backend:

```
'ndarray' object cannot be interpreted as an integer
  File "/home/marten/miniconda3/envs/pytme/lib/python3.11/site-packages/tme/matching_exhaustive.py", line 1254, in inner_function
    return_value = func(shared_memory_handler=smh, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marten/miniconda3/envs/pytme/lib/python3.11/site-packages/tme/matching_exhaustive.py", line 1342, in scan
    template=matching_data.template,
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marten/miniconda3/envs/pytme/lib/python3.11/site-packages/tme/matching_data.py", line 537, in template
    return template.reshape(self._output_template_shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 752, in cupy._core.core._ndarray_base.reshape
  File "cupy/_core/_routines_manipulation.pyx", line 81, in cupy._core._routines_manipulation._ndarray_reshape
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_Py_ssize_t
```

Seems the shape passed to cupy reshape is of type ndarray while I think it only allows tuples.

Perhaps I am doing something wrong input wise though. Let me know if you need more info!

Best,
Marten

**Comment by maurerv** [comment]
Hi @McHaillet,

Thank you for raising this, your diagnosis was spot on :)

I fixed this in the most recent commit (8e2a799cd00e24e73be02290d521d4744c45787a). This branch is usually stable, but this bug appeared to have slipped through since we are in between versions. If you are looking for a more stable source, please consider using the most recent version from PyPi: https://pypi.org/project/pytme/.

Best,
Valentin

**Comment by McHaillet** [comment]
Hi Valentin,
Great! I know did the pypi install and its working :)

I see the template and mask are by default padded, should I turn that off with `--no_fourier_padding` for a good comparison?

**Comment by maurerv** [comment]
Yes, for tomograms it usually makes sense to turn Fourier padding off. There should also be a warning in case you really should keep it on :)

If you use a similar splitting approach to the original PyTom, you could also tune the --memory_scaling or --ram parameter in match_template.py so that both tools compute a similar number of splits.

**Comment by McHaillet** [comment]
> Yes, for tomograms it usually makes sense to turn Fourier padding off. There should also be a warning in case you really should keep it on :)

Ah, thats handy!

> If you use a similar splitting approach to the original PyTom, you could also tune the --memory_scaling or --ram parameter in match_template.py so that both tools compute a similar number of splits.

Yes, I just allow a number of splits along each axis specified by the user. I guess you are splitting the volume into cubes always? Because the tomogram that I have should fit in GPU memory as a whole, but it is still being split in 4 tiles.

The template and mask are still padded from 80 voxels to 137 voxels. What is it needed for? Could I turn it off?

```
> Template Mask
  - Inital Shape:        (80, 80, 80)
  - Sampling Rate:       (13.79, 13.79, 13.79)
  - Final Shape:         (137, 137, 137)
```

**Comment by maurerv** [comment]
> The template and mask are still padded from 80 voxels to 137 voxels. What is it needed for? Could I turn it off?

By default, the template is assumed not to be in a centered box. You can turn this off using the --no_centering flag.

> Yes, I just allow a number of splits along each axis specified by the user. I guess you are splitting the volume into cubes always? Because the tomogram that I have should fit in GPU memory as a whole, but it is still being split in 4 tiles.

The splitting is done automatically with respect to template and target size plus some leniency to avoid running out of memory. However, for some GPU / data combinations, the split is not optimal. You could turn it off implicitly by setting --ram or --memory_scaling to a large value.

**Comment by McHaillet** [comment]
Thanks for the suggestions, I now got it to run without changing the boxes. Template and mask are at original size and the tomogram is one box! That should give a proper comparison.

Thanks for the quick reponses, will let you know what comes out!

**Comment by maurerv** [comment]
Great! I will close this issue for now :)

**Comment by McHaillet** [comment]
Hi Valentin, its been some time but I managed to run some tests. Could I get your mail to send you some details? Alternatively, you could also join the teamtomo zulip chat https://imagesc.zulipchat.com/#narrow/stream/426493-TeamTomo and we can chat there! Probably anyway nice to join for you as well as it is just a group of cryo-ET developers from all over :)

**Comment by maurerv** [comment]
Hi Marten, thank you for the invitation :) Feel free to drop an e-mail: valentin.maurer@embl-hamburg.de
