### ISSUE TITLE
Using pyTEM for single particle analysis

### ISSUE THREAD

**Issue by rsanchezgarc** [KosinskiLab/pyTME#8]
Hi,
Great package! I wonder if pyTME can be used for 2D classification or angular estimation in single particle analysis, where you have a stack of M 2D particles and another stack of  N 2D references, and you want to find, for each particle, the best matching reference (and the in-plane alignment).

From the API, I assume that it does not work on stacks of images, only on images, so you would need to have a double nested loop to iterate over particles and then over references, but I assume that this is quite inefficient, so I was wondering if there is an efficient way of implementing this use case using your package

Thanks,

**Comment by maurerv** [comment]
Hi @rsanchezgarc,

thank you for your interest in the project :)

I have been exploring this very use case and have a pilot implementation. While it is not yet in the public release, I would be happy to discuss it further.  Feel free to reach out to me at: valentin.maurer@embl-hamburg.de.
